[dataset]
data_files = ["./datasets/BikeNYC/NYC14_M16x8_T60_NewEnd.h5"]
holiday_file = ""
meteorol_file = ""
T = 24
len_closeness = 3
len_period = 1
len_trend = 1
; 24 * 28
len_test = 672
use_meta = true

[model]
nb_flow = 2
map_height = 16
map_width = 8
nb_residual_unit = 4

[learning]
epochs = 100
batch_size = 32
learning_rate = 0.001
smooth_l1_beta = 1.0
weight_decay = 0.05
max_lr = 0.002
pct_start = 0.10
